"""Pydantic schemas for agent tasks and planning."""

import json
from datetime import datetime

from pydantic import BaseModel, field_validator


class AgentTaskResponse(BaseModel):
    id: str
    task_type: str
    instruction: str
    status: str
    result: str | None = None
    error: str | None = None
    parent_task_id: str | None = None
    agent_type: str = "general"
    skill_chain: list[str] | None = None
    current_skill_index: int = 0
    progress: int = 0
    progress_message: str | None = None
    sub_task_count: int = 0
    completed_sub_tasks: int = 0
    todo_id: str | None = None
    payload: dict | None = None
    conversation_id: str | None = None
    message_id: str | None = None
    created_at: datetime
    started_at: datetime | None = None
    completed_at: datetime | None = None
    sub_tasks: list["AgentTaskResponse"] | None = None

    model_config = {"from_attributes": True}

    @field_validator("payload", mode="before")
    @classmethod
    def _parse_payload(cls, v: object) -> dict | None:
        if isinstance(v, str):
            try:
                return json.loads(v)
            except (json.JSONDecodeError, TypeError):
                return None
        return v  # type: ignore[return-value]

    @field_validator("skill_chain", mode="before")
    @classmethod
    def _parse_skill_chain(cls, v: object) -> list[str] | None:
        if isinstance(v, str):
            try:
                return json.loads(v)
            except (json.JSONDecodeError, TypeError):
                return None
        return v  # type: ignore[return-value]


# -- Plan schemas ------------------------------------------------------------


class PlanSubtask(BaseModel):
    title: str
    description: str | None = None
    estimated_minutes: int | None = None
    due_date: str | None = None
    depends_on_indices: list[int] = []


class PlanResponse(BaseModel):
    """Plan generated by the planner for a todo."""
    task_id: str
    todo_id: str
    summary: str
    suggested_root_due_date: str | None = None
    suggested_assignee: str | None = None       # legacy
    suggested_skills: list[str] | None = None   # new
    suggested_project_title: str | None = None
    subtasks: list[PlanSubtask] = []
    created_at: datetime

    # Computed display fields
    subtask_count: int = 0
    suggested_due_summary: str | None = None
    suggested_assignee_label: str | None = None   # legacy
    suggested_skills_labels: list[str] | None = None  # new
    suggested_project_label: str | None = None


class PlanApplyResponse(BaseModel):
    """Result of applying a plan to a todo."""
    todo_id: str
    created_subtask_ids: list[str] = []
    created_relationships: int = 0
    project_folder_created: str | None = None


class OrganizeRequest(BaseModel):
    """Trigger inbox organization for a todo."""
    pass


class DelegateRequest(BaseModel):
    """Delegate a todo to a skill (or legacy agent persona)."""
    skill_id: str | None = None                     # preferred
    agent_type: str | None = None                    # legacy fallback


class SkillResponse(BaseModel):
    """Public representation of a registered skill."""
    id: str
    name: str
    description: str
    tags: list[str] = []
