// ---------------------------------------------------------------------------
// API request/response types — re-exported from Zod schemas for validation
// All existing `import { ... } from '../types/api'` continue working unchanged
// ---------------------------------------------------------------------------

export type {
  TodoResponse,
  TodoCreate,
  TodoUpdate,
  TaskStatus,
  TaskRelationshipType,
  TaskRelationshipResponse,
  TaskRelationshipCreate,
  TaskRelationshipUpdate,
  GraphInsightScopeRole,
  GraphExecutionState,
  GraphDueRisk,
  TaskGraphInsightNode,
  TaskGraphInsightSummary,
  TaskGraphInsightIssue,
  TaskGraphInsightsResponse,
  ProjectTodoResponse,
  EventResponse,
  EventCreate,
  EventUpdate,
  ConversationResponse,
  StreamEventMeta,
  SettingsPayload,
  HealthResponse,
  CapabilitiesResponse,
  BulkTodoUpdate,
  AttachmentResponse,
  AdminOverviewResponse,
  AIConfigResponse,
  AITestResponse,
  ActivityResponse,
  SessionsResponse,
  ServerConfigResponse,
  DataOverviewResponse,
  PurgeResponse,
  ReindexResponse,
  BackupResponse,
  PlanSubtask,
  PlanProposalStatus,
  PlanChangeSetStatus,
  PlanVaultSyncStatus,
  PlanValidationIssue,
  PlanValidationResult,
  PlanProposalDiff,
  PlanProposalResponse,
  PlanResponse,
  PlanGenerateRequest,
  PlanApplyRequest,
  PlanDismissRequest,
  PlanDismissResponse,
  PlanApplyResponse,
  PlanUndoResponse,
  StalePlanProposalDetails,
  PlanProposalErrorResponse,
} from './schemas';
