export const queryKeys = {
  todos: ['todos'] as const,
  taskRelationships: ['task-relationships'] as const,
  taskGraphInsights: ['task-graph-insights'] as const,
  taskGraphInsightScope: (rootTaskId?: string | null) =>
    ['task-graph-insights', rootTaskId ?? 'all'] as const,
  planProposals: ['plan-proposals'] as const,
  latestPlanProposal: (todoId: string) => ['plan-proposals', 'latest', todoId] as const,
  planProposal: (proposalId: string) => ['plan-proposals', 'detail', proposalId] as const,
  events: ['events'] as const,
  calendarSubscription: ['calendar-subscription'] as const,
  conversations: ['conversations'] as const,
  projects: ['projects'] as const,
  project: (id: string) => ['projects', id] as const,
  executionProviders: ['execution-providers'] as const,
  skills: ['skills'] as const,
  reviews: ['reviews'] as const,
  reviewList: (status: string, projectId?: string | null) =>
    ['reviews', status, projectId ?? 'all'] as const,
  artifacts: (projectId: string) => ['artifacts', projectId] as const,
  runs: ['runs'] as const,
  runList: (projectId?: string | null) => ['runs', projectId ?? 'all'] as const,
  runEvents: (runId: string) => ['runs', runId, 'events'] as const,
  taskExecutionTelemetry: ['task-execution-telemetry'] as const,
  messages: (id: string) => ['messages', id] as const,
  today: ['today'] as const,
  attachments: (ownerId: string) => ['attachments', ownerId] as const,
  adminOverview: ['admin', 'overview'] as const,
  adminAI: ['admin', 'ai'] as const,
  adminActivity: ['admin', 'activity'] as const,
  adminSessions: ['admin', 'sessions'] as const,
  adminConfig: ['admin', 'config'] as const,
  adminData: ['admin', 'data'] as const,
  capabilities: ['capabilities'] as const,
  obsidianHealth: ['obsidian', 'health'] as const,
  obsidianQueue: ['obsidian', 'queue'] as const,
};
