"""baseline schema

Revision ID: 9927ab512428
Revises:
Create Date: 2026-08-27 13:21:18.432421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9927ab512428'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('project_todo_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_todo_id'], ['todos.id'], name='fk_conversations_project_todo_id', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index('idx_conversations_project_todo_id', ['project_todo_id'], unique=False)
        batch_op.create_index('idx_conversations_updated_at', ['updated_at'], unique=False)

    op.create_table('host_identity',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('host_id', sa.String(), nullable=False),
    sa.Column('private_key', sa.Text(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id')
    )
    op.create_table('paired_devices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('device_type', sa.String(), nullable=False),
    sa.Column('device_token', sa.String(), nullable=False),
    sa.Column('paired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('push_token', sa.Text(), nullable=True),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_token')
    )
    with op.batch_alter_table('paired_devices', schema=None) as batch_op:
        batch_op.create_index('idx_paired_devices_is_active', ['is_active'], unique=False)

    op.create_table('pairing_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claimed_by_device_id', sa.String(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('refresh_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('current_jti_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_refresh_sessions_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('idx_refresh_sessions_subject', ['subject'], unique=False)

    op.create_table('user_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('settings_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.create_index('idx_user_settings_user_id', ['user_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('idx_messages_conversation_id', ['conversation_id'], unique=False)
        batch_op.create_index('idx_messages_created_at', ['created_at'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('is_all_day', sa.Boolean(), nullable=False),
    sa.Column('reminder_minutes', sa.Integer(), nullable=True),
    sa.Column('recurrence_rule', sa.Text(), nullable=True),
    sa.Column('recurrence_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recurrence_exceptions', sa.Text(), nullable=True),
    sa.Column('recurring_event_id', sa.String(), nullable=True),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['recurring_event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('idx_events_conversation_id', ['conversation_id'], unique=False)
        batch_op.create_index('idx_events_end_time', ['end_time'], unique=False)
        batch_op.create_index('idx_events_start_time', ['start_time'], unique=False)

    op.create_table('todos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('assignee', sa.String(), nullable=True),
    sa.Column('enabled_skills', sa.Text(), nullable=True),
    sa.Column('inbox_state', sa.String(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('automation_error', sa.Text(), nullable=True),
    sa.Column('clarification_questions', sa.Text(), nullable=True),
    sa.Column('clarification_answers', sa.Text(), nullable=True),
    sa.Column('depends_on', sa.Text(), nullable=True),
    sa.Column('recurrence_rule', sa.Text(), nullable=True),
    sa.Column('recurrence_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recurrence_exceptions', sa.Text(), nullable=True),
    sa.Column('recurring_source_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['todos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recurring_source_id'], ['todos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.create_index('idx_todos_conversation_id', ['conversation_id'], unique=False)
        batch_op.create_index('idx_todos_due_date', ['due_date'], unique=False)
        batch_op.create_index('idx_todos_parent_id', ['parent_id'], unique=False)
        batch_op.create_index('idx_todos_recurrence_rule', ['recurrence_rule'], unique=False)
        batch_op.create_index('idx_todos_sort_order', ['sort_order'], unique=False)
        batch_op.create_index('idx_todos_source', ['source'], unique=False)
        batch_op.create_index('idx_todos_status', ['status'], unique=False)

    op.create_table('agent_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('parent_task_id', sa.String(), nullable=True),
    sa.Column('agent_type', sa.String(), nullable=False),
    sa.Column('skill_chain', sa.Text(), nullable=True),
    sa.Column('current_skill_index', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('progress_message', sa.Text(), nullable=True),
    sa.Column('sub_task_count', sa.Integer(), nullable=False),
    sa.Column('completed_sub_tasks', sa.Integer(), nullable=False),
    sa.Column('todo_id', sa.String(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['parent_task_id'], ['agent_tasks.id'], ),
    sa.ForeignKeyConstraint(['todo_id'], ['todos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_tasks', schema=None) as batch_op:
        batch_op.create_index('idx_agent_tasks_conversation_id', ['conversation_id'], unique=False)
        batch_op.create_index('idx_agent_tasks_parent', ['parent_task_id'], unique=False)
        batch_op.create_index('idx_agent_tasks_status', ['status'], unique=False)

    op.create_table('attachments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('todo_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['todo_id'], ['todos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index('idx_attachments_todo_id', ['todo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index('idx_attachments_todo_id')

    op.drop_table('attachments')
    with op.batch_alter_table('agent_tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_agent_tasks_status')
        batch_op.drop_index('idx_agent_tasks_parent')
        batch_op.drop_index('idx_agent_tasks_conversation_id')

    op.drop_table('agent_tasks')
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_index('idx_todos_status')
        batch_op.drop_index('idx_todos_source')
        batch_op.drop_index('idx_todos_sort_order')
        batch_op.drop_index('idx_todos_recurrence_rule')
        batch_op.drop_index('idx_todos_parent_id')
        batch_op.drop_index('idx_todos_due_date')
        batch_op.drop_index('idx_todos_conversation_id')

    op.drop_table('todos')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('idx_events_start_time')
        batch_op.drop_index('idx_events_end_time')
        batch_op.drop_index('idx_events_conversation_id')

    op.drop_table('events')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('idx_messages_created_at')
        batch_op.drop_index('idx_messages_conversation_id')

    op.drop_table('messages')
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_index('idx_user_settings_user_id')

    op.drop_table('user_settings')
    with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_refresh_sessions_subject')
        batch_op.drop_index('idx_refresh_sessions_expires_at')

    op.drop_table('refresh_sessions')
    op.drop_table('pairing_sessions')
    with op.batch_alter_table('paired_devices', schema=None) as batch_op:
        batch_op.drop_index('idx_paired_devices_is_active')

    op.drop_table('paired_devices')
    op.drop_table('host_identity')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('idx_conversations_updated_at')
        batch_op.drop_index('idx_conversations_project_todo_id')

    op.drop_table('conversations')
    # ### end Alembic commands ###
